### ISSUE TITLE
Support ajax methods

### ISSUE THREAD

**Issue by nafg** [jducoeur/jquery-facade#7]
I can't find any ajax methods in the facade library

**Comment by jducoeur** [comment]
That's true, and it's because I don't have any use for them myself (Querki uses Play's synthesized functions for its client/server communication).  This is a moderately substantial project to do right.  I would greatly welcome a PR for that; I'm somewhat unlikely to have time for it myself soon, since it's a fair pile of functions to go through...

**Comment by nafg** [comment]
Do you mean it uses play reverse routing from scalajs? How do you manage
that? And what does that have to do with how you invoke them?

**Comment by jducoeur** [comment]
First, I [extract all the Play routing stuff into the HTML script](https://github.com/jducoeur/Querki/blob/master/querki/scalajvm/app/views/client.scala.html#L45-L76) -- this uses Play's surprisingly-poorly-documented JavascriptReverseRoute functionality.

Then on the client side, I [wrap those generated Play calls in a facade](https://github.com/jducoeur/Querki/blob/master/querki/scalajs/src/main/scala/querki/comm/ClientRoutes.scala).  Actually, two -- a low-level facade and a high-level one.  And then _that_ [gets wrapped in an Autowire wrapper](https://github.com/jducoeur/Querki/blob/master/querki/scalajs/src/main/scala/querki/client/Client.scala), which is what the application code actually uses.

So between all that, I never directly touch jQuery's AJAX layer -- it's all hidden underneath the generated Play code.  Once I got it all running, it's worked without a hitch, so I've never even looked at anything else yet.  (That'll change once my backend gets websocket capabilities, but even then I'm going to be focusing on websocket communication rather than traditional AJAX...)

**Comment by jducoeur** [comment]
I should note, BTW, that this is why JQueryAjaxSettings and JQueryXHR _are_ implemented, even though none of the AJAX calls themselves are -- the Play stuff is using jQuery AJAX under the hood (I believe -- I haven't actually dug into it), and does expose those data structures.

**Comment by jducoeur** [comment]
Okay -- jquery-facade 1.0-RC1 now includes all of the Ajax functions that I know of.  Please open issues if you find problems with those...
