### ISSUE TITLE
jquery 2.2.1

### ISSUE THREAD

**Issue by mathieuleclaire** [jducoeur/jquery-facade#9]
Hi Justin,
did to you plan to move to jquery 2.2.1 ? I tried it, it works except for the cross compilation with scala 2.10.
Mathieu

**Comment by jducoeur** [comment]
Hmm -- hadn't noticed the version upgrade.  I might, but I'm also considering decoupling the facade from the jQuery library itself -- documenting how to link with jQuery instead of doing it automatically.  That would follow the way scalajs-jquery went, and I think their logic makes sense.

Anyway, I'll deal with this soon, one way or t'other.  Thanks for pointing it out...

**Comment by jducoeur** [comment]
Closing this as now moot -- I've just released 1.0-RC1, and switched to saying that the application should declare its own jsDependency for the underlying jQuery library, so that jquery-facade isn't a bottleneck any more.

**Comment by mathieuleclaire** [comment]
Excellent ! Thanks !
